### ISSUE TITLE
Crear Wiki

### ISSUE THREAD

**Issue by claraconstans** [Equip-33/Joc-Web#6]
i. Introducció
ii. Descripció del disseny del joc
iii. Descripció de les parts més rellevants de la implementació
iv. Conclusions i problemes trobats
v. Manual d’usuari

**Comment by claraconstans** [comment]
Introducció i Descripció del disseny del joc FET

**Comment by claraconstans** [comment]
Manual d'usuari FET

**Comment by u1981148** [comment]
Descripció de les parts més rellevants de la implementació FET

**Comment by claraconstans** [comment]
Conclusions i problemes trobats FET

**Comment by claraconstans** [comment]
Repassat i acabat definitivament
